### ISSUE TITLE
Need CSV support

### ISSUE THREAD

**Issue by ryman1** [BlackBox-CSP/password-tools#16]
It's a pain to put these stats in a report with the current output.

**Comment by bandrel** [comment]
Do you want a CSV option given as a command line argument?  Also I presume you are referring to crackedhashstats.py

**Comment by ryman1** [comment]
yes, crackedhashstats.py. 

always output to terminal. output to csv as well when a cli arg is added

**Comment by ryman1** [comment]
also, you don't have to do these features unless you want to, I'm putting them in here to keep track of the ideas at least.

**Comment by ryman1** [comment]
https://github.com/BlackBox-CSP/password-tools/tree/csvsupport

**Comment by bandrel** [comment]
Can you checkout https://github.com/BlackBox-CSP/password-tools/tree/csvsupport2 and let me know what you think? I know the CSV naming is a bit clunky and i'm open to suggestions

**Comment by ryman1** [comment]
Looking good, I would recommend making a directory structure around the csv support.  i.e. Date/time ran > History/Modern/Combined > individual csvs .

Output_csv() seems over-indented.

Looks like statsgen being separate is making this a headache.

**Comment by ryman1** [comment]
Closing for now. Don't really need this.
