### ISSUE TITLE
service accounts

### ISSUE THREAD

**Issue by ryman1** [BlackBox-CSP/password-tools#17]
possibly add the ability to return cracked accounts that appear to be service accounts (contain svc, service, server)

maybe have other embedded searches for other important account types like _sql_ _exch_ _sharepoint_

**Comment by bandrel** [comment]
What tool are you referencing?  Cracked hash stats?  If so are you talking about a separate section that gives statistics of a subgroup based on an optional input string?    OR just limits all output to the give input string and ignores the rest of the options?

**Comment by ryman1** [comment]
Yes I'm referring to cracked hash stats. As far as the rest of your
questions, I'll try replying when I'm not on my cell... It might be a while.

**Comment by ryman1** [comment]
I was thinking more along the lines of having a separate section (maybe called Interesting Cracked Accounts) that could be activated by its own cli switch. The extra section could display usernames and (optionally?) passwords of accounts that might be of special interest.

I'm not dead set on this feature, but I think it might be handy for huge datasets.

**Comment by ryman1** [comment]
Implemented https://github.com/BlackBox-CSP/password-tools/pull/36
